// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/reading_list.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "bookapi/internal/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReadingListRepository is a mock of ReadingListRepository interface.
type MockReadingListRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReadingListRepositoryMockRecorder
}

// MockReadingListRepositoryMockRecorder is the mock recorder for MockReadingListRepository.
type MockReadingListRepositoryMockRecorder struct {
	mock *MockReadingListRepository
}

// NewMockReadingListRepository creates a new mock instance.
func NewMockReadingListRepository(ctrl *gomock.Controller) *MockReadingListRepository {
	mock := &MockReadingListRepository{ctrl: ctrl}
	mock.recorder = &MockReadingListRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadingListRepository) EXPECT() *MockReadingListRepositoryMockRecorder {
	return m.recorder
}

// ListReadingListByStatus mocks base method.
func (m *MockReadingListRepository) ListReadingListByStatus(ctx context.Context, userID, status string, limit, offset int) ([]entity.Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReadingListByStatus", ctx, userID, status, limit, offset)
	ret0, _ := ret[0].([]entity.Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReadingListByStatus indicates an expected call of ListReadingListByStatus.
func (mr *MockReadingListRepositoryMockRecorder) ListReadingListByStatus(ctx, userID, status, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReadingListByStatus", reflect.TypeOf((*MockReadingListRepository)(nil).ListReadingListByStatus), ctx, userID, status, limit, offset)
}

// UpsertReadingListItem mocks base method.
func (m *MockReadingListRepository) UpsertReadingListItem(ctx context.Context, userID, isbn, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertReadingListItem", ctx, userID, isbn, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertReadingListItem indicates an expected call of UpsertReadingListItem.
func (mr *MockReadingListRepositoryMockRecorder) UpsertReadingListItem(ctx, userID, isbn, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertReadingListItem", reflect.TypeOf((*MockReadingListRepository)(nil).UpsertReadingListItem), ctx, userID, isbn, status)
}
