// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/rating.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRatingRepository is a mock of RatingRepository interface.
type MockRatingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepositoryMockRecorder
}

// MockRatingRepositoryMockRecorder is the mock recorder for MockRatingRepository.
type MockRatingRepositoryMockRecorder struct {
	mock *MockRatingRepository
}

// NewMockRatingRepository creates a new mock instance.
func NewMockRatingRepository(ctrl *gomock.Controller) *MockRatingRepository {
	mock := &MockRatingRepository{ctrl: ctrl}
	mock.recorder = &MockRatingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepository) EXPECT() *MockRatingRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdateRating mocks base method.
func (m *MockRatingRepository) CreateOrUpdateRating(ctx context.Context, userID, isbn string, star int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateRating", ctx, userID, isbn, star)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateRating indicates an expected call of CreateOrUpdateRating.
func (mr *MockRatingRepositoryMockRecorder) CreateOrUpdateRating(ctx, userID, isbn, star interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateRating", reflect.TypeOf((*MockRatingRepository)(nil).CreateOrUpdateRating), ctx, userID, isbn, star)
}

// GetBookRating mocks base method.
func (m *MockRatingRepository) GetBookRating(ctx context.Context, isbn string) (float64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookRating", ctx, isbn)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookRating indicates an expected call of GetBookRating.
func (mr *MockRatingRepositoryMockRecorder) GetBookRating(ctx, isbn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookRating", reflect.TypeOf((*MockRatingRepository)(nil).GetBookRating), ctx, isbn)
}

// GetUserRating mocks base method.
func (m *MockRatingRepository) GetUserRating(ctx context.Context, userID, isbn string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRating", ctx, userID, isbn)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRating indicates an expected call of GetUserRating.
func (mr *MockRatingRepositoryMockRecorder) GetUserRating(ctx, userID, isbn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRating", reflect.TypeOf((*MockRatingRepository)(nil).GetUserRating), ctx, userID, isbn)
}

// GetUserRatingStats mocks base method.
func (m *MockRatingRepository) GetUserRatingStats(ctx context.Context, userID string) (float64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRatingStats", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserRatingStats indicates an expected call of GetUserRatingStats.
func (mr *MockRatingRepositoryMockRecorder) GetUserRatingStats(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRatingStats", reflect.TypeOf((*MockRatingRepository)(nil).GetUserRatingStats), ctx, userID)
}
