// Code generated by MockGen. DO NOT EDIT.
// Source: internal/book/ports.go

// Package book is a generated GoMock package.
package book

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetByISBN mocks base method.
func (m *MockRepository) GetByISBN(ctx context.Context, isbn string) (Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByISBN", ctx, isbn)
	ret0, _ := ret[0].(Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByISBN indicates an expected call of GetByISBN.
func (mr *MockRepositoryMockRecorder) GetByISBN(ctx, isbn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByISBN", reflect.TypeOf((*MockRepository)(nil).GetByISBN), ctx, isbn)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, q Query) ([]Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q)
	ret0, _ := ret[0].([]Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, q)
}

// UpsertFromIngest mocks base method.
func (m *MockRepository) UpsertFromIngest(ctx context.Context, book *Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFromIngest", ctx, book)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFromIngest indicates an expected call of UpsertFromIngest.
func (mr *MockRepositoryMockRecorder) UpsertFromIngest(ctx, book interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFromIngest", reflect.TypeOf((*MockRepository)(nil).UpsertFromIngest), ctx, book)
}
