// Code generated by MockGen. DO NOT EDIT.
// Source: internal/catalog/postgres_repo.go

// Package catalog is a generated GoMock package.
package catalog

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetAuthorUpdatedAt mocks base method.
func (m *MockRepository) GetAuthorUpdatedAt(ctx context.Context, key string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorUpdatedAt", ctx, key)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorUpdatedAt indicates an expected call of GetAuthorUpdatedAt.
func (mr *MockRepositoryMockRecorder) GetAuthorUpdatedAt(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorUpdatedAt", reflect.TypeOf((*MockRepository)(nil).GetAuthorUpdatedAt), ctx, key)
}

// GetBookUpdatedAt mocks base method.
func (m *MockRepository) GetBookUpdatedAt(ctx context.Context, isbn13 string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookUpdatedAt", ctx, isbn13)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookUpdatedAt indicates an expected call of GetBookUpdatedAt.
func (mr *MockRepositoryMockRecorder) GetBookUpdatedAt(ctx, isbn13 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookUpdatedAt", reflect.TypeOf((*MockRepository)(nil).GetBookUpdatedAt), ctx, isbn13)
}

// GetByISBN mocks base method.
func (m *MockRepository) GetByISBN(ctx context.Context, isbn13 string) (Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByISBN", ctx, isbn13)
	ret0, _ := ret[0].(Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByISBN indicates an expected call of GetByISBN.
func (mr *MockRepositoryMockRecorder) GetByISBN(ctx, isbn13 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByISBN", reflect.TypeOf((*MockRepository)(nil).GetByISBN), ctx, isbn13)
}

// GetTotalAuthors mocks base method.
func (m *MockRepository) GetTotalAuthors(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAuthors", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAuthors indicates an expected call of GetTotalAuthors.
func (mr *MockRepositoryMockRecorder) GetTotalAuthors(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAuthors", reflect.TypeOf((*MockRepository)(nil).GetTotalAuthors), ctx)
}

// GetTotalBooks mocks base method.
func (m *MockRepository) GetTotalBooks(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalBooks", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalBooks indicates an expected call of GetTotalBooks.
func (mr *MockRepositoryMockRecorder) GetTotalBooks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalBooks", reflect.TypeOf((*MockRepository)(nil).GetTotalBooks), ctx)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, q SearchQuery) ([]Book, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q)
	ret0, _ := ret[0].([]Book)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, q)
}

// UpsertAuthor mocks base method.
func (m *MockRepository) UpsertAuthor(ctx context.Context, author *Author, rawJSON []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAuthor", ctx, author, rawJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertAuthor indicates an expected call of UpsertAuthor.
func (mr *MockRepositoryMockRecorder) UpsertAuthor(ctx, author, rawJSON interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAuthor", reflect.TypeOf((*MockRepository)(nil).UpsertAuthor), ctx, author, rawJSON)
}

// UpsertBook mocks base method.
func (m *MockRepository) UpsertBook(ctx context.Context, book *Book, rawJSON []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBook", ctx, book, rawJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBook indicates an expected call of UpsertBook.
func (mr *MockRepositoryMockRecorder) UpsertBook(ctx, book, rawJSON interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBook", reflect.TypeOf((*MockRepository)(nil).UpsertBook), ctx, book, rawJSON)
}
